# Generated by Django 3.1 on 2020-09-19 16:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Learn_App', '0003_mydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
